### ISSUE TITLE
Зеркальный режим задней камеры

### ISSUE THREAD

**Issue by AntonRomanchuk** [boba-nopasaran-dr2800/Kitchen#1]
Здравствуйте!
Купил регистратор a800s и камеру к нему RC05.
Только при установке заметил тот факт, что задняя камера зеркалит картинку(как и следует делать для задней камеры). Но я хотел установить эту камеру спереди, не учел этот момент при покупке. 

Есть ли в прошивке возможность как-нибудь обратно отзеркалить изображение с задней камеры? Будет хорошо, даже если отзеркалится картинка с основной камеры.

Заранее спасибо за ответ!

**Comment by 0xb0ba** [comment]
я не нашел ни в прошивке ни в сдк упоминаний о зеркалировании :(

**Comment by AntonRomanchuk** [comment]
Спасибо за ответ! А что насчет Camera.Menu.UpsideDown=Normal? Если есть возможность найти альтернативное значение - было бы круто. Я бы мог перевернуть камеру и отзеркалить её по вертикали

**Comment by 0xb0ba** [comment]
я не нашел в коде, где бы это использовалось
